let cart = [];
let currentCategory = 'starter';

// DOM Elements
const menuContainer = document.getElementById('menu-container');
const tabBtns = document.querySelectorAll('.tab-btn');
const cartCount = document.querySelector('.cart-count');
const cartTrigger = document.getElementById('cart-trigger');
const cartModal = document.getElementById('cart-modal');
const closeCart = document.getElementById('close-cart');
const cartItemsList = document.getElementById('cart-items-list');
const cartTotal = document.getElementById('cart-total');
const placeOrderBtn = document.getElementById('place-order-btn');
const tableNoInput = document.getElementById('table-no');

// Initialize App
function init() {
    loadMenu();
    setupListeners();
}

// Load Menu from Firebase
// Load Menu from JSON (Generated by Netlify Build)
function loadMenu() {
    fetch('menu.json')
        .then(response => {
            if (!response.ok) throw new Error("Menu file not found");
            return response.json();
        })
        .then(data => {
            renderMenu(data);
        })
        .catch(err => {
            console.error("Failed to load menu:", err);
            menuContainer.innerHTML = '<p style="grid-column: 1/-1; text-align: center;">Menu is currently unavailable. Please check back later.</p>';
        });
}

// Render Menu Items
function renderMenu(items) {
    if (!items) {
        menuContainer.innerHTML = '<p style="grid-column: 1/-1; text-align: center;">No items found. Visit the admin panel to add some!</p>';
        return;
    }

    menuContainer.innerHTML = '';
    const filteredItems = Object.entries(items)
        .filter(([id, item]) => item.category === currentCategory && item.available !== false);

    filteredItems.forEach(([id, item]) => {
        const itemEl = document.createElement('div');
        itemEl.className = 'menu-item glass';
        itemEl.innerHTML = `
            <img src="${item.image || 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400'}" alt="${item.name}" class="item-img">
            <div class="item-info">
                <span class="item-name">${item.name}</span>
                <span class="item-price">₹${item.price}</span>
            </div>
            <p class="item-desc">${item.description}</p>
            <button class="add-btn" onclick="addToCart('${id}', '${item.name}', ${item.price})">Add to Order</button>
        `;
        menuContainer.appendChild(itemEl);
    });
}

// Listeners
function setupListeners() {
    tabBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            tabBtns.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            currentCategory = btn.dataset.category;
            // Re-render based on current category (data is already loaded/cached ideally, but here we just re-fetch or assume renderMenu handles filtering if we passed the full data. 
            // Wait, typically we should store the data in a variable to avoid re-fetching.
            // Let's modify renderMenu to use a global variable or re-fetch.
            // For simplicity, let's re-fetch or just assume renderMenu was called with data.
            // Actually, the original code fetched from Firebase on click? No, listeners were setup.
            // Let's just reload the menu.
            loadMenu();
        });
    });

    cartTrigger.addEventListener('click', () => {
        renderCart();
        cartModal.classList.add('active');
    });

    closeCart.addEventListener('click', () => {
        cartModal.classList.remove('active');
    });

    placeOrderBtn.addEventListener('click', placeOrder);
}

// Cart Logic
window.addToCart = (id, name, price) => {
    const existing = cart.find(item => item.id === id);
    if (existing) {
        existing.quantity += 1;
    } else {
        cart.push({ id, name, price, quantity: 1 });
    }
    updateCartUI();
};

function renderCart() {
    cartItemsList.innerHTML = '';
    let total = 0;

    if (cart.length === 0) {
        cartItemsList.innerHTML = '<p style="text-align: center; color: var(--text-muted)">Your cart is empty.</p>';
        cartTotal.innerText = '₹0';
        return;
    }

    cart.forEach((item, index) => {
        total += item.price * item.quantity;
        const itemEl = document.createElement('div');
        itemEl.className = 'cart-item';
        itemEl.innerHTML = `
            <div>
                <div style="font-weight: 700">${item.name}</div>
                <div style="font-size: 0.8rem; color: var(--text-muted)">₹${item.price}</div>
            </div>
            <div class="cart-item-qty">
                <button class="qty-btn" onclick="updateQty(${index}, -1)">-</button>
                <span>${item.quantity}</span>
                <button class="qty-btn" onclick="updateQty(${index}, 1)">+</button>
            </div>
        `;
        cartItemsList.appendChild(itemEl);
    });

    cartTotal.innerText = `₹${total}`;
}

window.updateQty = (index, delta) => {
    cart[index].quantity += delta;
    if (cart[index].quantity <= 0) {
        cart.splice(index, 1);
    }
    renderCart();
    updateCartUI();
};

function updateCartUI() {
    const totalItems = cart.reduce((sum, item) => sum + item.quantity, 0);
    cartCount.innerText = totalItems;
    cartCount.style.display = totalItems > 0 ? 'flex' : 'none';
}

// Place Order
function placeOrder() {
    const tableNo = tableNoInput.value;
    if (!tableNo) {
        alert('Please enter your table number!');
        return;
    }

    if (cart.length === 0) {
        alert('Your cart is empty!');
        return;
    }

    const order = {
        tableNo,
        items: cart,
        timestamp: Date.now(),
        status: 'pending'
    };

    db.ref('orders').push(order).then(() => {
        alert('Order placed successfully! The kitchen is onto it.');
        cart = [];
        updateCartUI();
        cartModal.classList.remove('active');
        tableNoInput.value = '';
    }).catch(err => {
        console.error(err);
        alert('Error placing order. Please check your connection.');
    });
}

// Initial Call
init();
