let cart = [];
let currentCategory = 'starter';
let currentTable = null;
let sessionId = null;
let menuData = null;
let isProcessingOrder = false;

// DOM Elements
const menuContainer = document.getElementById('menu-container');
const tabBtns = document.querySelectorAll('.tab-btn');
const cartCount = document.getElementById('bar-cart-count');
const cartTotalBar = document.getElementById('bar-cart-total');
const bottomBar = document.getElementById('bottom-bar');
const cartModal = document.getElementById('cart-modal');
const closeCart = document.getElementById('close-cart');
const cartItemsList = document.getElementById('cart-items-list');
const cartTotal = document.getElementById('cart-total');
const placeOrderBtn = document.getElementById('place-order-btn');
const tableNoInput = document.getElementById('welcome-table-no');

// Initialize App
// Initialize App
function init() {
    checkLicense();
    loadMenu();
    setupListeners();
    checkSession();
    updateRequestBillVisibility();
}

const LICENSE_ID = 'caferesto-demo';

function checkLicense() {
    const overlay = document.getElementById('license-overlay');
    const msg = document.getElementById('license-msg');

    db.ref('licenses/' + LICENSE_ID).on('value', snapshot => {
        const data = snapshot.val();

        if (!data) {
            // If No license exists yet, create a trial one for the demo
            const trialExpiry = new Date();
            trialExpiry.setDate(trialExpiry.getDate() + 30); // 30 days trial
            db.ref('licenses/' + LICENSE_ID).set({
                clientName: "Demo Cafe & Resto",
                expiryDate: trialExpiry.toISOString().split('T')[0],
                isActive: true
            });
            return;
        }

        const expiryDate = new Date(data.expiryDate);
        const isExpired = expiryDate < new Date() && data.expiryDate !== '';
        const isSuspended = data.isActive === false;

        if (isSuspended) {
            overlay.style.display = 'flex';
            msg.innerText = "Your service has been temporarily suspended by the administrator.";
        } else if (isExpired) {
            overlay.style.display = 'flex';
            msg.innerText = `Your subscription expired on ${expiryDate.toLocaleDateString()}. Please renew to continue.`;
        } else {
            overlay.style.display = 'none';
        }
    });
}

// Load Menu from Firebase
// Load Menu from JSON (Generated by Netlify Build)
function loadMenu() {
    if (menuData) {
        renderMenu(menuData);
        return;
    }

    fetch('menu.json')
        .then(response => {
            if (!response.ok) throw new Error("Menu file not found");
            return response.json();
        })
        .then(data => {
            menuData = data;
            renderMenu(data);
        })
        .catch(err => {
            console.error("Failed to load menu:", err);
            menuContainer.innerHTML = '<p style="grid-column: 1/-1; text-align: center;">Menu is currently unavailable. Please check back later.</p>';
        });
}

// Render Menu Items
function renderMenu(items) {
    if (!items) {
        menuContainer.innerHTML = '<p style="grid-column: 1/-1; text-align: center;">No items found. Visit the admin panel to add some!</p>';
        return;
    }

    menuContainer.innerHTML = '';
    const filteredItems = Object.entries(items)
        .filter(([id, item]) => item.category === currentCategory && item.available !== false);

    filteredItems.forEach(([id, item]) => {
        const itemEl = document.createElement('div');
        itemEl.className = 'menu-item glass';

        let actionsHtml = '';
        if (item.variants && item.variants.length > 0) {
            // Variant selection as Chips
            const chipsHtml = item.variants.map((v, idx) => `
                <button class="variant-chip ${idx === 0 ? 'active' : ''}" 
                    data-price="${v.price}" 
                    data-variant="${v.name}"
                    onclick="selectVariant(this, '${id}')">
                    ${v.name}
                </button>
            `).join('');

            actionsHtml = `
                <div class="variant-chips" id="chips-${id}">
                    ${chipsHtml}
                </div>
                <button class="add-btn" onclick="addSelectedVariantToCart('${id}', '${item.name}')">Add to Order</button>
            `;
        } else {
            // Direct add
            actionsHtml = `<button class="add-btn" onclick="addToCart('${id}', '${item.name}', ${item.price})">Add to Order</button>`;
        }

        itemEl.innerHTML = `
            <img src="${item.image || 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400'}" alt="${item.name}" class="item-img">
            <div class="item-info">
                <span class="item-name">${item.name}</span>
                <span class="item-price" id="price-${id}">${item.variants && item.variants.length > 0 ? '₹' + item.variants[0].price : '₹' + item.price}</span>
            </div>
            <p class="item-desc">${item.description}</p>
            <div class="item-actions">
                ${actionsHtml}
            </div>
        `;
        menuContainer.appendChild(itemEl);
    });
}

// Variant Selection Logic
window.selectVariant = (chip, id) => {
    // Remove active class from all chips in this container
    const container = document.getElementById(`chips-${id}`);
    container.querySelectorAll('.variant-chip').forEach(c => c.classList.remove('active'));

    // Add active class to clicked chip
    chip.classList.add('active');

    // Update price display
    const priceDisplay = document.getElementById(`price-${id}`);
    priceDisplay.innerText = `₹${chip.dataset.price}`;
};

window.addSelectedVariantToCart = (id, baseName) => {
    const activeChip = document.querySelector(`#chips-${id} .variant-chip.active`);
    if (!activeChip) return;

    const variantName = activeChip.dataset.variant;
    const variantPrice = parseFloat(activeChip.dataset.price);

    addToCart(id, `${baseName} (${variantName})`, variantPrice, variantName);
};

// Listeners
function setupListeners() {
    tabBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            tabBtns.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            currentCategory = btn.dataset.category;
            // Re-render based on current category (data is already loaded/cached ideally, but here we just re-fetch or assume renderMenu handles filtering if we passed the full data. 
            // Wait, typically we should store the data in a variable to avoid re-fetching.
            // Let's modify renderMenu to use a global variable or re-fetch.
            // For simplicity, let's re-fetch or just assume renderMenu was called with data.
            // Actually, the original code fetched from Firebase on click? No, listeners were setup.
            // Let's just reload the menu.
            loadMenu();
        });
    });

    const barCartTrigger = document.getElementById('bar-cart-trigger');
    const barOpenCartBtn = document.getElementById('bar-open-cart-btn');

    barCartTrigger.addEventListener('click', () => {
        renderCart();
        updateRequestBillVisibility();
        cartModal.classList.add('active');
    });

    barOpenCartBtn.addEventListener('click', () => {
        renderCart();
        updateRequestBillVisibility();
        cartModal.classList.add('active');
    });

    closeCart.addEventListener('click', () => {
        cartModal.classList.remove('active');
    });

    placeOrderBtn.addEventListener('click', placeOrder);
    document.getElementById('request-bill-btn').addEventListener('click', requestBill);
    document.getElementById('bar-request-bill-btn').addEventListener('click', requestBill);
    document.getElementById('start-order-btn').addEventListener('click', handleTableSelection);
}

// Session & Table Locking Logic
function checkSession() {
    const storedTable = localStorage.getItem('caferesto_table');
    const storedSession = localStorage.getItem('caferesto_session');
    const storedPhone = localStorage.getItem('caferesto_phone');
    const storedName = localStorage.getItem('caferesto_name');

    if (storedTable && storedSession) {
        // Verify with Firebase if this session is still valid
        db.ref('tables/table_' + storedTable).once('value').then(snapshot => {
            const data = snapshot.val();
            if (data && data.status === 'occupied' && data.sessionId === storedSession) {
                // Valid session
                currentTable = storedTable;
                sessionId = storedSession;
                window.customerPhone = storedPhone;
                window.customerName = storedName;
                document.getElementById('welcome-modal').classList.remove('active');
                if (bottomBar) bottomBar.classList.add('active');
                console.log(`Resumed session for ${window.customerName} at Table ${currentTable}`);
                watchSessionStatus();
            } else {
                // Session invalid/expired
                localStorage.removeItem('caferesto_table');
                localStorage.removeItem('caferesto_session');
                localStorage.removeItem('caferesto_phone');
                localStorage.removeItem('caferesto_name');
                document.getElementById('welcome-modal').classList.add('active');
            }
        });
    } else {
        document.getElementById('welcome-modal').classList.add('active');
        if (bottomBar) bottomBar.classList.remove('active');
    }
}

function updateRequestBillVisibility() {
    const btnModal = document.getElementById('request-bill-btn');
    const btnBar = document.getElementById('bar-request-bill-btn');

    if (sessionId) {
        db.ref('sessions/' + sessionId).on('value', snapshot => {
            const data = snapshot.val();
            const showBtn = data && data.items && data.items.length > 0;

            [btnModal, btnBar].forEach(btn => {
                if (!btn) return;
                btn.style.display = showBtn ? 'block' : 'none';

                if (data && data.status === 'bill_requested') {
                    btn.disabled = true;
                    btn.innerHTML = '<i class="fas fa-check"></i> BILL REQUESTED';
                    btn.style.opacity = '0.7';
                } else {
                    btn.disabled = false;
                    btn.innerHTML = btn === btnBar ? '<i class="fas fa-file-invoice-dollar"></i> BILL' : 'REQUEST BILL';
                    btn.style.opacity = '1';
                }
            });
        });
    }
}

function handleTableSelection() {
    const input = document.getElementById('welcome-table-no');
    const phoneInput = document.getElementById('welcome-phone');
    const nameInput = document.getElementById('welcome-name');
    const errorMsg = document.getElementById('table-error');
    const startBtn = document.getElementById('start-order-btn');
    const tableNo = input.value;
    const phone = phoneInput.value;
    const name = nameInput.value;

    if (!name || name.trim().length < 2) {
        errorMsg.innerText = "Please enter your name";
        errorMsg.style.display = 'block';
        return;
    }

    if (!tableNo || tableNo < 1) {
        errorMsg.innerText = "Please enter a valid table number";
        errorMsg.style.display = 'block';
        return;
    }

    if (!phone || phone.length < 10) {
        errorMsg.innerText = "Please enter a valid WhatsApp number";
        errorMsg.style.display = 'block';
        return;
    }

    // UX Enhancement: Loading State
    const originalBtnContent = startBtn.innerHTML;
    startBtn.disabled = true;
    startBtn.innerHTML = '<i class="fas fa-circle-notch fa-spin"></i> VERIFYING...';
    errorMsg.style.display = 'none';

    const resetBtn = () => {
        startBtn.disabled = false;
        startBtn.innerHTML = originalBtnContent;
    };

    const newSessionId = Date.now().toString() + Math.random().toString(36).substr(2, 9);
    const tableRef = db.ref('tables/table_' + tableNo);

    tableRef.once('value').then(snapshot => {
        const data = snapshot.val();

        if (data && data.status === 'occupied') {
            const existingSession = localStorage.getItem('caferesto_session');
            // Check if it's OUR session (maybe page reload/reopen)
            if (data.sessionId === existingSession) {
                // Re-attach
                currentTable = tableNo;
                sessionId = data.sessionId;
                window.customerPhone = data.customerPhone || phone;
                window.customerName = data.customerName || name;
                document.getElementById('welcome-modal').classList.remove('active');
                watchSessionStatus();
                resetBtn();
            } else {
                errorMsg.innerText = `Table ${tableNo} is currently occupied.`;
                errorMsg.style.display = 'block';
                resetBtn();
            }
        } else {
            // Table is free - Lock it!
            const sessionInit = {
                tableNo: tableNo,
                customerName: name,
                customerPhone: phone,
                status: 'active',
                startTime: Date.now(),
                total: 0,
                items: []
            };

            db.ref('sessions/' + newSessionId).set(sessionInit).then(() => {
                tableRef.set({
                    status: 'occupied',
                    sessionId: newSessionId,
                    timestamp: Date.now()
                }).then(() => {
                    currentTable = tableNo;
                    sessionId = newSessionId;
                    window.customerPhone = phone;
                    window.customerName = name;
                    localStorage.setItem('caferesto_table', currentTable);
                    localStorage.setItem('caferesto_session', sessionId);
                    localStorage.setItem('caferesto_phone', phone);
                    localStorage.setItem('caferesto_name', name);
                    localStorage.setItem('caferesto_name', name);
                    document.getElementById('welcome-modal').classList.remove('active');
                    if (bottomBar) bottomBar.classList.add('active');
                    watchSessionStatus();
                    resetBtn();
                });
            }).catch(err => {
                console.error(err);
                errorMsg.innerText = "Connection error. Please try again.";
                errorMsg.style.display = 'block';
                resetBtn();
            });
        }
    }).catch(err => {
        console.error(err);
        errorMsg.innerText = "Error connecting to server.";
        errorMsg.style.display = 'block';
        resetBtn();
    });
}

function watchSessionStatus() {
    if (!currentTable || !sessionId) return;

    const tableRef = db.ref('tables/table_' + currentTable);
    tableRef.on('value', snapshot => {
        const data = snapshot.val();
        if (!data || data.status !== 'occupied' || data.sessionId !== sessionId) {
            // Table was released or session changed
            tableRef.off(); // Stop listening
            alert("Your session has ended or the table has been released. Redirecting...");
            localStorage.removeItem('caferesto_table');
            localStorage.removeItem('caferesto_session');
            localStorage.removeItem('caferesto_phone');
            localStorage.removeItem('caferesto_name');
            if (bottomBar) bottomBar.classList.remove('active');
            window.location.reload();
        }
    });
}

// Cart Logic
window.addToCart = (id, displayName, price, variant = null) => {
    const cartId = variant ? `${id}-${variant}` : id;
    const existing = cart.find(item => item.cartId === cartId);

    if (existing) {
        existing.quantity += 1;
    } else {
        cart.push({
            id,
            cartId,
            name: displayName,
            price,
            quantity: 1,
            variant: variant
        });
    }
    updateCartUI();
    showToast(`Added ${displayName} to order`);
};

function showToast(message) {
    const toast = document.getElementById('toast');
    const toastMsg = toast.querySelector('span');
    toastMsg.innerText = message;

    toast.classList.add('show');

    // Hide after 2 seconds
    setTimeout(() => {
        toast.classList.remove('show');
    }, 2000);
}

function renderCart() {
    cartItemsList.innerHTML = '';
    let total = 0;

    if (cart.length === 0) {
        cartItemsList.innerHTML = '<p style="text-align: center; color: var(--text-muted)">Your cart is empty.</p>';
        cartTotal.innerText = '₹0';
        return;
    }

    cart.forEach((item, index) => {
        total += item.price * item.quantity;
        const itemEl = document.createElement('div');
        itemEl.className = 'cart-item';
        itemEl.innerHTML = `
            <div>
                <div style="font-weight: 700">${item.name}</div>
                <div style="font-size: 0.8rem; color: var(--text-muted)">₹${item.price}</div>
            </div>
            <div class="cart-item-qty">
                <button class="qty-btn" onclick="updateQty(${index}, -1)">-</button>
                <span>${item.quantity}</span>
                <button class="qty-btn" onclick="updateQty(${index}, 1)">+</button>
            </div>
        `;
        cartItemsList.appendChild(itemEl);
    });

    cartTotal.innerText = `₹${total}`;
}

window.updateQty = (index, delta) => {
    cart[index].quantity += delta;
    if (cart[index].quantity <= 0) {
        cart.splice(index, 1);
    }
    renderCart();
    updateCartUI();
};

function updateCartUI() {
    const totalItems = cart.reduce((sum, item) => sum + item.quantity, 0);
    const totalPrice = cart.reduce((sum, item) => sum + (item.price * item.quantity), 0);

    if (cartCount) cartCount.innerText = totalItems;
    if (cartTotalBar) cartTotalBar.innerText = `₹${totalPrice}`;

    // Animate count if it changes
    if (totalItems > 0) {
        cartCount.parentElement.style.transform = 'scale(1.2)';
        setTimeout(() => {
            cartCount.parentElement.style.transform = 'scale(1)';
        }, 200);
    }
}

// Place Order
function placeOrder() {
    if (isProcessingOrder) return;

    if (!currentTable) {
        alert("Error: No table selected. Please refresh.");
        return;
    }

    if (cart.length === 0) {
        alert('Your cart is empty!');
        return;
    }

    // Protection UI
    isProcessingOrder = true;
    const originalBtnContent = placeOrderBtn.innerHTML;
    placeOrderBtn.disabled = true;
    placeOrderBtn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> PLACING ORDER...';

    const resetBtn = () => {
        isProcessingOrder = false;
        placeOrderBtn.disabled = false;
        placeOrderBtn.innerHTML = originalBtnContent;
    };

    const order = {
        tableNo: currentTable,
        items: cart,
        timestamp: Date.now(),
        status: 'pending',
        sessionId: sessionId,
        customerPhone: window.customerPhone || localStorage.getItem('caferesto_phone')
    };

    // Verify table is still active
    db.ref('tables/table_' + currentTable).once('value').then(snapshot => {
        const tableData = snapshot.val();

        if (!tableData || tableData.status !== 'occupied' || tableData.sessionId !== sessionId) {
            alert('Your session has expired or the table is no longer active. Please refresh.');
            localStorage.removeItem('caferesto_table');
            localStorage.removeItem('caferesto_session');
            window.location.reload();
            return;
        }

        // Calculate order total
        const orderTotal = cart.reduce((sum, item) => sum + (item.price * item.quantity), 0);

        // 1. Send to Kitchen
        db.ref('orders').push(order).then(() => {
            // 2. Update Session History for Billing
            const sessionRef = db.ref('sessions/' + sessionId);
            sessionRef.once('value').then(snapshot => {
                const sessionData = snapshot.val() || {
                    tableNo: currentTable,
                    items: [],
                    total: 0,
                    status: 'active',
                    startTime: Date.now()
                };

                const existingItems = sessionData.items || [];

                cart.forEach(cartItem => {
                    const existingItem = existingItems.find(i => i.cartId === cartItem.cartId);
                    if (existingItem) {
                        existingItem.quantity += cartItem.quantity;
                    } else {
                        existingItems.push(cartItem);
                    }
                });

                sessionData.items = existingItems;
                sessionData.total = (sessionData.total || 0) + orderTotal;
                sessionData.customerPhone = order.customerPhone; // Ensure phone is in session
                sessionData.customerName = window.customerName || localStorage.getItem('caferesto_name'); // Ensure name is in session
                sessionData.lastOrderTime = Date.now();

                sessionRef.set(sessionData).then(() => {
                    alert('Order placed successfully! The kitchen is onto it.');

                    cart = [];
                    updateCartUI();
                    updateRequestBillVisibility();
                    cartModal.classList.remove('active');
                    if (tableNoInput) tableNoInput.value = '';
                    resetBtn();
                });
            });
        }).catch(err => {
            console.error(err);
            alert('Error placing order. Please check your connection.');
            resetBtn();
        });
    }).catch(err => {
        console.error("Table verification failed:", err);
        alert("Unable to verify table session. Please try again.");
        resetBtn();
    });
}

function requestBill() {
    if (!sessionId) return;

    if (confirm("Would you like to request your bill now?")) {
        const btnModal = document.getElementById('request-bill-btn');
        const btnBar = document.getElementById('bar-request-bill-btn');

        [btnModal, btnBar].forEach(btn => {
            if (btn) {
                btn.disabled = true;
                btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> REQUESTING...';
            }
        });

        db.ref('sessions/' + sessionId).update({
            status: 'bill_requested',
            billRequestedAt: Date.now()
        }).then(() => {
            // updateRequestBillVisibility listener will handle the UI update
            alert("Your bill request has been sent to the counter. Please wait while we process it.");
        }).catch(err => {
            console.error("Error requesting bill:", err);
            updateRequestBillVisibility(); // Reset button states
            alert("Failed to request bill. Please try again.");
        });
    }
}

// Initial Call
init();
