let cart = [];
let currentCategory = 'starter';
let currentTable = null;
let sessionId = null;

// DOM Elements
const menuContainer = document.getElementById('menu-container');
const tabBtns = document.querySelectorAll('.tab-btn');
const cartCount = document.querySelector('.cart-count');
const cartTrigger = document.getElementById('cart-trigger');
const cartModal = document.getElementById('cart-modal');
const closeCart = document.getElementById('close-cart');
const cartItemsList = document.getElementById('cart-items-list');
const cartTotal = document.getElementById('cart-total');
const placeOrderBtn = document.getElementById('place-order-btn');
const tableNoInput = document.getElementById('welcome-table-no');

// Initialize App
// Initialize App
function init() {
    loadMenu();
    setupListeners();
    checkSession();
}

// Load Menu from Firebase
// Load Menu from JSON (Generated by Netlify Build)
function loadMenu() {
    fetch('menu.json')
        .then(response => {
            if (!response.ok) throw new Error("Menu file not found");
            return response.json();
        })
        .then(data => {
            renderMenu(data);
        })
        .catch(err => {
            console.error("Failed to load menu:", err);
            menuContainer.innerHTML = '<p style="grid-column: 1/-1; text-align: center;">Menu is currently unavailable. Please check back later.</p>';
        });
}

// Render Menu Items
function renderMenu(items) {
    if (!items) {
        menuContainer.innerHTML = '<p style="grid-column: 1/-1; text-align: center;">No items found. Visit the admin panel to add some!</p>';
        return;
    }

    menuContainer.innerHTML = '';
    const filteredItems = Object.entries(items)
        .filter(([id, item]) => item.category === currentCategory && item.available !== false);

    filteredItems.forEach(([id, item]) => {
        const itemEl = document.createElement('div');
        itemEl.className = 'menu-item glass';
        itemEl.innerHTML = `
            <img src="${item.image || 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400'}" alt="${item.name}" class="item-img">
            <div class="item-info">
                <span class="item-name">${item.name}</span>
                <span class="item-price">₹${item.price}</span>
            </div>
            <p class="item-desc">${item.description}</p>
            <button class="add-btn" onclick="addToCart('${id}', '${item.name}', ${item.price})">Add to Order</button>
        `;
        menuContainer.appendChild(itemEl);
    });
}

// Listeners
function setupListeners() {
    tabBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            tabBtns.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            currentCategory = btn.dataset.category;
            // Re-render based on current category (data is already loaded/cached ideally, but here we just re-fetch or assume renderMenu handles filtering if we passed the full data. 
            // Wait, typically we should store the data in a variable to avoid re-fetching.
            // Let's modify renderMenu to use a global variable or re-fetch.
            // For simplicity, let's re-fetch or just assume renderMenu was called with data.
            // Actually, the original code fetched from Firebase on click? No, listeners were setup.
            // Let's just reload the menu.
            loadMenu();
        });
    });

    cartTrigger.addEventListener('click', () => {
        renderCart();
        cartModal.classList.add('active');
    });

    closeCart.addEventListener('click', () => {
        cartModal.classList.remove('active');
    });

    placeOrderBtn.addEventListener('click', placeOrder);

    document.getElementById('start-order-btn').addEventListener('click', handleTableSelection);
}

// Session & Table Locking Logic
function checkSession() {
    const storedTable = localStorage.getItem('caferesto_table');
    const storedSession = localStorage.getItem('caferesto_session');

    if (storedTable && storedSession) {
        // Verify with Firebase if this session is still valid
        db.ref('tables/table_' + storedTable).once('value').then(snapshot => {
            const data = snapshot.val();
            if (data && data.status === 'occupied' && data.sessionId === storedSession) {
                // Valid session
                currentTable = storedTable;
                sessionId = storedSession;
                document.getElementById('welcome-modal').classList.remove('active');
                console.log(`Resumed session for Table ${currentTable}`);
            } else {
                // Session invalid/expired
                localStorage.removeItem('caferesto_table');
                localStorage.removeItem('caferesto_session');
                document.getElementById('welcome-modal').classList.add('active');
            }
        });
    } else {
        document.getElementById('welcome-modal').classList.add('active');
    }
}

function handleTableSelection() {
    const input = document.getElementById('welcome-table-no');
    const errorMsg = document.getElementById('table-error');
    const tableNo = input.value;

    if (!tableNo || tableNo < 1) {
        errorMsg.innerText = "Please enter a valid table number";
        errorMsg.style.display = 'block';
        return;
    }

    const newSessionId = Date.now().toString() + Math.random().toString(36).substr(2, 9);
    const tableRef = db.ref('tables/table_' + tableNo);

    tableRef.once('value').then(snapshot => {
        const data = snapshot.val();

        if (data && data.status === 'occupied') {
            // Check if it's OUR session (maybe page reload/reopen)
            if (data.sessionId === localStorage.getItem('caferesto_session')) {
                // Re-attach
                currentTable = tableNo;
                sessionId = data.sessionId;
                document.getElementById('welcome-modal').classList.remove('active');
            } else {
                errorMsg.innerText = `Table ${tableNo} is currently occupied.`;
                errorMsg.style.display = 'block';
            }
        } else {
            // Table is free - Lock it!
            const sessionInit = {
                tableNo: tableNo,
                status: 'active',
                startTime: Date.now(),
                total: 0,
                items: []
            };

            db.ref('sessions/' + newSessionId).set(sessionInit).then(() => {
                tableRef.set({
                    status: 'occupied',
                    sessionId: newSessionId,
                    timestamp: Date.now()
                }).then(() => {
                    currentTable = tableNo;
                    sessionId = newSessionId;
                    localStorage.setItem('caferesto_table', currentTable);
                    localStorage.setItem('caferesto_session', sessionId);
                    document.getElementById('welcome-modal').classList.remove('active');
                });
            });
        }
    });
}

// Cart Logic
window.addToCart = (id, name, price) => {
    const existing = cart.find(item => item.id === id);
    if (existing) {
        existing.quantity += 1;
    } else {
        cart.push({ id, name, price, quantity: 1 });
    }
    updateCartUI();
    showToast(`Added ${name} to order`);
};

function showToast(message) {
    const toast = document.getElementById('toast');
    const toastMsg = toast.querySelector('span');
    toastMsg.innerText = message;

    toast.classList.add('show');

    // Hide after 2 seconds
    setTimeout(() => {
        toast.classList.remove('show');
    }, 2000);
}

function renderCart() {
    cartItemsList.innerHTML = '';
    let total = 0;

    if (cart.length === 0) {
        cartItemsList.innerHTML = '<p style="text-align: center; color: var(--text-muted)">Your cart is empty.</p>';
        cartTotal.innerText = '₹0';
        return;
    }

    cart.forEach((item, index) => {
        total += item.price * item.quantity;
        const itemEl = document.createElement('div');
        itemEl.className = 'cart-item';
        itemEl.innerHTML = `
            <div>
                <div style="font-weight: 700">${item.name}</div>
                <div style="font-size: 0.8rem; color: var(--text-muted)">₹${item.price}</div>
            </div>
            <div class="cart-item-qty">
                <button class="qty-btn" onclick="updateQty(${index}, -1)">-</button>
                <span>${item.quantity}</span>
                <button class="qty-btn" onclick="updateQty(${index}, 1)">+</button>
            </div>
        `;
        cartItemsList.appendChild(itemEl);
    });

    cartTotal.innerText = `₹${total}`;
}

window.updateQty = (index, delta) => {
    cart[index].quantity += delta;
    if (cart[index].quantity <= 0) {
        cart.splice(index, 1);
    }
    renderCart();
    updateCartUI();
};

function updateCartUI() {
    const totalItems = cart.reduce((sum, item) => sum + item.quantity, 0);
    cartCount.innerText = totalItems;
    cartCount.style.display = totalItems > 0 ? 'flex' : 'none';
}

// Place Order
// Place Order
function placeOrder() {
    if (!currentTable) {
        alert("Error: No table selected. Please refresh.");
        return;
    }

    if (cart.length === 0) {
        alert('Your cart is empty!');
        return;
    }

    const order = {
        tableNo: currentTable,
        items: cart,
        timestamp: Date.now(),
        status: 'pending',
        sessionId: sessionId
    };

    // Verify table is still active
    db.ref('tables/table_' + currentTable).once('value').then(snapshot => {
        const tableData = snapshot.val();

        if (!tableData || tableData.status !== 'occupied' || tableData.sessionId !== sessionId) {
            alert('Your session has expired or the table is no longer active. Please refresh.');
            // Optional: reset local state
            localStorage.removeItem('caferesto_table');
            localStorage.removeItem('caferesto_session');
            window.location.reload();
            return;
        }

        // Calculate order total
        const orderTotal = cart.reduce((sum, item) => sum + (item.price * item.quantity), 0);

        // 1. Send to Kitchen
        db.ref('orders').push(order).then(() => {
            // 2. Update Session History for Billing
            const sessionRef = db.ref('sessions/' + sessionId);
            sessionRef.once('value').then(snapshot => {
                const sessionData = snapshot.val() || {
                    tableNo: currentTable,
                    items: [],
                    total: 0,
                    status: 'active',
                    startTime: Date.now()
                };

                sessionData.items = [...(sessionData.items || []), ...cart];
                sessionData.total = (sessionData.total || 0) + orderTotal;
                sessionData.lastOrderTime = Date.now();

                sessionRef.set(sessionData).then(() => {
                    alert('Order placed successfully! The kitchen is onto it.');
                    cart = [];
                    updateCartUI();
                    cartModal.classList.remove('active');
                    if (tableNoInput) tableNoInput.value = '';
                });
            });
        }).catch(err => {
            console.error(err);
            alert('Error placing order. Please check your connection.');
        });
    }).catch(err => {
        console.error("Table verification failed:", err);
        alert("Unable to verify table session. Please try again.");
    });
}

// Initial Call
init();
